# Angular Frontend Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 2 # Number of replicas
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: hmidahmed049/frontend:latest # Image for the frontend application
          imagePullPolicy: Always
          ports:
            - containerPort: 80 # Typical HTTP port for frontend apps

# Angular Frontend Service
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: ClusterIP # Set to ClusterIP for internal access within Kind
